execution_env=local
#execution_env=remote


appURL=https://tutorialsninja.com/demo/
email=vishal143@gmail.com
password=Vishal@123
searchProductName=iPhone


incognito_mode=false
headless_mode=false


